language: ruby
rvm:
  - 2.0.0-p353
script:
  - cp config/travis.database.yml config/database.yml
  - psql -c 'create database ruvetia_test;' -U postgres
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rake
