# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: af9490c294fad080d56bd754ea7653d476cdf0cc52a1faaa5551be7c2d0f3e0180faf19a0f4ea7a49ee162dba0699bb93587b7257d0d59b11f8f19e73e7ac08d

test:
  secret_key_base: a1be20ffbd196539607e82999cba6ec0d1a781d577b3bf14247dee5af6a20e6798df8bbd9f3e888e14477a600ce48d740305b0cd6cb9ac2db7636fff09221fae

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
